# https://travis-ci.org

language: cpp
compiler:
  - gcc
  - clang
env:
  - QT=qt5 CONFIG=shared
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev
script:
script:
  - qmake -qt=qt5 trianglemesh.pro -r -v
  - qmake -qt=qt5 trianglemesh.pro -r
  - make
