# https://travis-ci.org

language: cpp

install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository --yes ppa:lttng/daily
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config
  - sudo apt-get install -qq qt4-qmake qtbase4-dev qtdeclarative4-dev
script:
  - make release && cd release
  - qmake ../trianglemesh.pro -o Makefile
  - make
